
export const celebrities = [
    {
      name: "Brad Pitt",
      imageSrc: "/images/Brad_Pitt-69858.jpg",
      imageAlt: "Brad Pitt",
      videoPoster: "/images/imageforthevid.webp",
      videoSrcMp4: "/images/Watch Brad Pitt Thank His Kids During 2020 Oscars Speech.mp4",
      videoSrcOgg: "/images/Watch Brad Pitt Thank His Kids During 2020 Oscars Speech.ogg",
      videoSrcWebm: "/images/Watch Brad Pitt Thank His Kids During 2020 Oscars Speech.webm",
      videoDescription: "Watch Brad Pitt's speech at the 2020 Oscars",
      born:"December 18, 1963 in Shawnee, Oklahoma, USA" ,
      birthname:"William Bradley Pitt" ,
      nickname:"Brad",
      height:"1.80 m",
      img1:"/images/bradpitt1.jpg",
      img2:"/images/bradpitt2.jpg",
      img3:"/images/bradpitt3.jpg",
      img4:"/images/bradpitt4.jpg",
      img5:"/images/bradpitt5.jpg",
      img6:"/images/bradpitt6.jpg",
      img7:"/images/bradpitt7.jpg",
      img8:"/images/bradpitt8.jpg",
      img9:"/images/bradpitt9.jpg",
      img10:"/images/bradpitt10.jpg",


      birth: "Born December 18, 1963",
      parents: "(William Alvin Pitt/Jane Etta Pitt)",
      school: "High School: Kickapoo High School",
      university: "University of Missouri",
      address: "Oklahoma and raised in Missouri",
      careerbefore: "Chauffeur limousines",
      firstcareer: "Fight Club",
      currentcareer: "Wolfs",
      marriages: "Freed man",
      children: "Biological children (Zahara Marley)",
    },
    {
      name: "Morgan Freeman",
      imageSrc: "/images/morgan freemanS.jpg",
      imageAlt: "Morgan Freeman",
      videoPoster: "/images/poster-morgan-freemanS.jpg",
      videoSrcMp4: "/images/morgan freeman `s best acting ,NO.1 movie (IMDB) and best scene of TSR.mp4",
      videoSrcOgg: "/images/morgan freeman `s best acting ,NO.1 movie (IMDB) and best scene of TSR.ogg",
      videoSrcWebm: "/images/morgan freeman `s best acting ,NO.1 movie (IMDB) and best scene of TSR.webm",
      videoDescription: "Watch Morgan Freeman acting in The Shawshank Redemption",
      born: "June 1, 1937 in Memphis, Tennessee, USA",
      birthname: "Morgan Freeman",
      nickname: "Morgan",
      height: "1.88 m",
      img1: "/images/morganfreeman1.jpg",
      img2: "/images/morganfreeman2.jpg",
      img3: "/images/morganfreeman3.jpg",
      img4: "/images/morganfreeman4.jpg",
      img5: "/images/morganfreeman5.jpg",
      img6: "/images/morganfreeman6.jpg",
      img7: "/images/morganfreeman7.jpg",
      img8: "/images/morganfreeman8.jpg",
      img9: "/images/morganfreeman9.jpg",
      img10: "/images/morganfreeman10.jpg",

      birth: "Born June 1, 1937",
      parents: "(Porterfield Freeman/Mayme Edna)",
      school: "Broad Street High School",
      university: "Did not attend university",
      address: "Tennessee",
      careerbefore: "U.S. Air Force",
      firstcareer: "Driving Miss Daisy",
      currentcareer: "Actor and producer",
      marriages: "Myrna Colley",
      children: "Deena",
    },
    {
      name: "Angelina Jolie",
      imageSrc: "/images/angelina jolieS.jpg",
      imageAlt: "Angelina Jolie",
      videoPoster: "/images/posterangelinaS.jpg",
      videoSrcMp4: "/images/Angelina Jolie Will Always Land on Her Feet .mp4",
      videoSrcOgg: "/images/Angelina Jolie Will Always Land on Her Feet .ogg",
      videoSrcWebm: "/images/Angelina Jolie Will Always Land on Her Feet .webm",
      videoDescription: "Watch Angelina Jolie interview with W magazine",
      born: "June 4, 1975 in Los Angeles, California, USA",
      birthname: "Angelina Jolie Voight",
      nickname: "Angie",
      height: "1.69 m",
      img1: "/images/angelinajolie1.jpg",
      img2: "/images/angelinajolie2.jpg",
      img3: "/images/angelinajolie3.jpg",
      img4: "/images/angelinajolie4.jpg",
      img5: "/images/angelinajolie5.jpg",
      img6: "/images/angelinajolie6.jpg",
      img7: "/images/angelinajolie7.jpg",
      img8: "/images/angelinajolie8.jpg",
      img9: "/images/angelinajolie9.jpg",
      img10: "/images/angelinajolie10.jpg",


      birth: "Born June 4, 1975",
      parents: "(Jon Voight/Marcheline Bertrand)",
      school: "Beverly Hills",
      university: "Lee Strasberg",
      address: "Los Angeles",
      careerbefore: "Worked as a model",
      firstcareer: "Hackers",
      currentcareer: "Filmmaker",
      marriages: "Brad Pitt",
      children: "Zahara",
    },
    {
      name: "Jenna Ortega",
      imageSrc: "/images/jenna ortegaS.jpg",
      imageAlt: "Jenna Ortega",
      videoPoster: "/images/jennaposterS.jpg",
      videoSrcMp4: "/images/jennaVid.mp4",
      videoSrcOgg: "/images/jennaVid.ogg",
      videoSrcWebm: "/images/jennaVid.webm",
      videoDescription: "Watch Jenna Ortega with Adidas",
      born: "September 27, 2002 in Coachella Valley, California, USA",
    birthname: "Jenna Marie Ortega",
    nickname: "Jenna",
    height: "1.55 m",
    img1: "/images/jennaortega1.jpg",
    img2: "/images/jennaortega2.jpg",
    img3: "/images/jennaortega3.jpg",
    img4: "/images/jennaortega4.jpg",
    img5: "/images/jennaortega5.jpg",
    img6: "/images/jennaortega6.jpg",
    img7: "/images/jennaortega7.jpg",
    img8: "/images/jennaortega8.jpg",
    img9: "/images/jennaortega9.jpg",
    img10: "/images/jennaortega10.jpg",
    birth: "Born September 27, 2002",
      parents: "(Natalie Ortega/Edward Ortega)",
      school: "Homeschooled due to her acting career.",
      university: "Did not attend university",
      address: "Los Angeles",
      careerbefore: "Appeared in commercials as a child",
      firstcareer: "Jane the Virgin (2014)",
      currentcareer: "Actress",
      marriages: "Not married.",
      children: "No children",
    },
    {
      name: "Theo James",
      imageSrc: "/images/theo jamesS.jpg",
      imageAlt: "Theo James",
      videoPoster: "/images/postertheoS.webp",
      videoSrcMp4: "/images/Range Rover Sport .mp4",
      videoSrcOgg: "/images/Range Rover Sport .ogg",
      videoSrcWebm: "/images/Range Rover Sport .webm",
      videoDescription: "Introducing Theo James for Range Rover Sport",
      born:"December 16, 1984 in Oxford, England" ,
      birthname:"Theodore Peter James Kinnaird Taptiklis", 
      nickname:"Theo",
      height:"1.85 m",
      img1:"/images/theojames1.jpg",
      img2:"/images/theojames2.jpg",
      img3:"/images/theojames3.jpg",
      img4:"/images/theojames4.jpg",
      img5:"/images/theojames5.jpg",
      img6:"/images/theojames6.jpg",
      img7:"/images/theojames7.jpg",
      img8:"/images/theojames8.jpg",
      img9:"/images/theojames9.jpg",
      img10:"/images/theojames10.jpg",

      birth: "Born on December 16, 1984",
      parents: "(William Alvin Pitt/Jane Etta Pitt)",
      school: "Bristol Old Vic Theatre School",
      university: "University of Nottingham",
      address: "Oklahoma and raised in Missouri",
      careerbefore: "Worked in retail and as a bartender.",
      firstcareer: "Divergent",
      currentcareer: "Actor in film and television, and occasional producer.",
      marriages: "Married Ruth Kearney in 2018.",
      children: "No children",
    },
    {

      name: "Millie Bobby Brown",
      imageSrc: "/images/millieS.jpg",
      imageAlt: "Millie Bobby Brown",
      videoPoster: "/images/postermillieS.jpg",
      videoSrcMp4: "/images/Millie Bobby Brown Ranks her haircuts .mp4",
      videoSrcOgg: "/Millie Bobby Brown Ranks her haircuts .ogg",
      videoSrcWebm: "/Millie Bobby Brown Ranks her haircuts .webm",
      videoDescription: "Millie Bobby Brown and her dog Winnie rank Millie's haircuts",
      born: "February 19, 2004 in Marbella, Spain",
      birthname: "Millie Bobby Brown",
      nickname: "Millie",
      height: "1.63 m",
      img1: "/images/milliebobbybrown1.jpg",
      img2: "/images/milliebobbybrown2.jpg",
      img3: "/images/milliebobbybrown3.jpg",
      img4: "/images/milliebobbybrown4.jpg",
      img5: "/images/milliebobbybrown5.jpg",
      img6: "/images/milliebobbybrown6.jpg",
      img7: "/images/milliebobbybrown7.jpg",
      img8: "/images/milliebobbybrown8.jpg",
      img9: "/images/milliebobbybrown9.jpg",
      img10: "/images/milliebobbybrown10.jpg",


      birth: "Born February 19, 2004",
      parents: "(Robert/Kelly Brown)",
      school: "Homeschooled while pursuing acting.",
      university: "Did not attend university",
      address: "Marbella, Spain",
      careerbefore: "Participated in local theater productions.",
      firstcareer: "Stranger Things",
      currentcareer: "Producer",
      marriages: "Not married",
      children: "No children",
    },






    {
      name: "Adele",
      imageSrc: "/images/adeleS.webp",
      imageAlt: "Adele",
      videoPoster: "/images/posteradeleS.jpg",
      videoSrcMp4: "/images/Adele Being a Songwriting Genius for 5 minutes.mp4",
      videoSrcOgg: "/Adele Being a Songwriting Genius for 5 minutes.ogg",
      videoSrcWebm: "/Adele Being a Songwriting Genius for 5 minutes.webm",
      videoDescription: "Adele Being a Songwriting Genius for 5 minutes",
      born: "May 5, 1988 in Tottenham, London, England",
      birthname: "Adele Laurie Blue Adkins",
      nickname: "Adele",
      height: "1.75 m",
      img1: "/images/adele1.jpg",
      img2: "/images/adele2.jpg",
      img3: "/images/adele3.jpg",
      img4: "/images/adele4.jpg",
      img5: "/images/adele5.jpg",
      img6: "/images/adele6.jpg",
      img7: "/images/adele7.jpg",
      img8: "/images/adele8.jpg",
      img9: "/images/adele9.jpg",
      img10: "/images/adele10.jpg",


      birth: "Born May 5, 1988",
      parents: "(Mark Evans/ Penny Adkins)",
      school: "The BRIT School for Performing Arts and Technology",
      university: "N/A",
      address: "Tottenham, London, England",
      careerbefore: "Worked as a waitress.",
      firstcareer: "19",
      currentcareer: "Singer-songwriter",
      marriages: "Not married",
      children: "One son, Angelo",
    },
    {
      name: "Billie Eilish",
      imageSrc: "/images/billieS.jpg",
      imageAlt: "Billie Eilish",
      videoPoster: "/images/posterbillieS.jpg",
      videoSrcMp4: "/images/Billie Eilish_ Same Interview, The Eighth Year (Coming Soon).mp4",
      videoSrcOgg: "/Billie Eilish_ Same Interview, The Eighth Year (Coming Soon).ogg",
      videoSrcWebm: "/Billie Eilish_ Same Interview, The Eighth Year (Coming Soon).webm",
      videoDescription: "Billie Eilish Same Interview, The Eighth Year",
      born: "December 18, 2001 in Los Angeles, California, USA",
      birthname: "Billie Eilish Pirate Baird O'Connell",
      nickname: "Billie",
      height: "1.61 m",
      img1: "/images/billieeilish1.jpg",
      img2: "/images/billieeilish2.jpg",
      img3: "/images/billieeilish3.jpg",
      img4: "/images/billieeilish4.jpg",
      img5: "/images/billieeilish5.jpg",
      img6: "/images/billieeilish6.jpg",
      img7: "/images/billieeilish7.jpg",
      img8: "/images/billieeilish8.jpg",
      img9: "/images/billieeilish9.jpg",
      img10: "/images/billieeilish10.jpg",



      birth: "Born December 18, 2001",
      parents: "(Maggie Baird/Patrick O'Connell)",
      school: "High School: Highland Park High School",
      university: "N/A",
      address: "Los Angeles, California, USA",
      careerbefore: "Worked as a model.",
      firstcareer: "Ocean Eyes",
      currentcareer: "Pop artist",
      marriages: "Not married",
      children: "No children",
    },
    {
      name: "Taylor Swift",
      imageSrc: "/images/taylorS.jpg",
      imageAlt: "Taylor Swift",
      videoPoster: "/images/postertaylorS.jpg",
      videoSrcMp4: "/images/Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About .mp4",
      videoSrcOgg: "/Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About .ogg",
      videoSrcWebm: "/Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About .webm",
      videoDescription: "Taylor Swift Talks About How The ‘All Too Well (10 Minute Version)’ Came About",
      born: "December 13, 1989 in Reading, Pennsylvania, USA",
      birthname: "Taylor Alison Swift",
      nickname: "Taylor",
      height: "1.80 m",
      img1: "/images/taylorswift1.jpg",
      img2: "/images/taylorswift2.jpg",
      img3: "/images/taylorswift3.jpg",
      img4: "/images/taylorswift4.jpg",
      img5: "/images/taylorswift5.jpg",
      img6: "/images/taylorswift6.jpg",
      img7: "/images/taylorswift7.jpg",
      img8: "/images/taylorswift8.jpg",
      img9: "/images/taylorswift9.jpg",
      img10: "/images/taylorswift10.jpg",


      birth: "Born December 13, 1989",
      parents: "(Scott Kingsley Swift/Andrea Gardner Swift)",
      school: "High School: Hendersonville High School",
      university: "N/A",
      address: "Wyomissing, Pennsylvania, USA",
      careerbefore: "N/A",
      firstcareer: "Taylor Swift",
      currentcareer: "Singer-songwriter",
      marriages: "Not married",
      children: "No children",
    },
    {
      name: "The Weeknd",
      imageSrc: "/images/the weekndS.jpg",
      imageAlt: "The Weeknd",
      videoPoster: "/images/postertheS.jpg",
      videoSrcMp4: "/images/The Idol I Press Conference I The Weeknd and the _Dark Side_ of the music Industry I Cannes 2023.mp4",
      videoSrcOgg: "/The Idol I Press Conference I The Weeknd and the _Dark Side_ of the music Industry I Cannes 2023.ogg",
      videoSrcWebm: "/The Idol I Press Conference I The Weeknd and the _Dark Side_ of the music Industry I Cannes 2023.webm",
      videoDescription: "The Weeknd and the _Dark Side_ of the music Industry",
      born: "February 16, 1990 in Toronto, Ontario, Canada",
      birthname: "Abel Makkonen Tesfaye",
      nickname: "The Weeknd",
      height: "1.73 m",
      img1: "/images/theweeknd1.jpg",
      img2: "/images/theweeknd2.jpg",
      img3: "/images/theweeknd3.jpg",
      img4: "/images/theweeknd4.jpg",
      img5: "/images/theweeknd5.jpg",
      img6: "/images/theweeknd6.jpg",
      img7: "/images/theweeknd7.jpg",
      img8: "/images/theweeknd8.jpg",
      img9: "/images/theweeknd9.jpg",
      img10: "/images/theweeknd10.jpg",



      birth: "Born February 16, 1990",
      parents: "(Abel Tesfaye)",
      school: "Weston Collegiate Institute",
      university: "N/A",
      address: "Toronto, Ontario, Canada",
      careerbefore: "N/A",
      firstcareer: "Kiss Land",
      currentcareer: "R&B artist",
      marriages: "Not married",
      children: "No children",
    },
    {
      name: "Lana Del Rey",
      imageSrc: "/images/lanaS.avif",
      imageAlt: "Lana Del Rey",
      videoPoster: "/images/posterlanaS.jpg",
      videoSrcMp4: "/images/Lana Del Rey talks new album 'Lasso', the world going country, and her plans for Reading & Leeds.mp4",
      videoSrcOgg: "/Lana Del Rey talks new album 'Lasso', the world going country, and her plans for Reading & Leeds.ogg",
      videoSrcWebm: "/Lana Del Rey talks new album 'Lasso', the world going country, and her plans for Reading & Leeds.webm",
      videoDescription: "Lana Del Rey talks new album the world going country",
      born: "June 21, 1985 in Manhattan, New York City, USA",
      birthname: "Elizabeth Woolridge Grant",
      nickname: "Lana Del Rey",
      height: "1.70 m",
      img1: "/images/lanadelrey1.jpg",
      img2: "/images/lanadelrey2.jpg",
      img3: "/images/lanadelrey3.jpg",
      img4: "/images/lanadelrey4.jpg",
      img5: "/images/lanadelrey5.jpg",
      img6: "/images/lanadelrey6.jpg",
      img7: "/images/lanadelrey7.jpg",
      img8: "/images/lanadelrey8.jpg",
      img9: "/images/lanadelrey9.jpg",
      img10: "/images/lanadelrey10.jpg",



      birth: "Born June 21, 1985",
      parents: "(Robert Grant ORA/Patricia Ann Hill)",
      school: "N/A",
      university: "N/A",
      address: "New York City, New York, USA",
      careerbefore: "N/A",
      firstcareer: "Born to Die",
      currentcareer: "Singer-songwriter",
      marriages: "Not married",
      children: "No children",
    },
    {
      name: "Rihanna",
      imageSrc: "/images/RihannaS.webp",
      imageAlt: "Rihanna",
      videoPoster: "/images/posterrihannaS.jpg",
      videoSrcMp4: "/images/Rihanna ‘Grateful’ for Accomplishments From the Past Year.mp4",
      videoSrcOgg: "/Rihanna ‘Grateful’ for Accomplishments From the Past Year.ogg",
      videoSrcWebm: "/Rihanna ‘Grateful’ for Accomplishments From the Past Year.webm",
      videoDescription: "Rihanna ‘Grateful’ for Accomplishments From the Past Year",
      born: "February 20, 1988 in Saint Michael, Barbados",
      birthname: "Robyn Rihanna Fenty",
      nickname: "Rihanna",
      height: "1.73 m",
      img1: "/images/rihanna1.jpg",
      img2: "/images/rihanna2.jpg",
      img3: "/images/rihanna3.jpg",
      img4: "/images/rihanna4.jpg",
      img5: "/images/rihanna5.jpg",
      img6: "/images/rihanna6.jpg",
      img7: "/images/rihanna7.jpg",
      img8: "/images/rihanna8.jpg",
      img9: "/images/rihanna9.jpg",
      img10: "/images/rihanna10.jpg",
      birth: "Born February 20, 1988",
      parents: "(Ronald Fenty/Monica Braithwaite)",
      school: "Charles F. Broome Memorial Primary School",
      university: "N/A",
      address: "Saint Michael, Barbados",
      careerbefore: "N/A",
      firstcareer: "Music of the Sun",
      currentcareer: "Pop and R&B artist",
      marriages: "Not married",
      children: "One son, RZA Athelstan.",
    },






    {
      name: "Lionel Messi",
      imageSrc: "/images/messiS.jpg",
      imageAlt: "Lionel Messi",
      videoPoster: "/images/postermesiiS.webp",
      videoSrcMp4: "/images/LIONEL MESSI MAGIC STEALS THE SHOW .mp4",
      videoSrcOgg: "/LIONEL MESSI MAGIC STEALS THE SHOW .ogg",
      videoSrcWebm: "/LIONEL MESSI MAGIC STEALS THE SHOW .webm",
      videoDescription: "LIONEL MESSI MAGIC STEALS THE SHOW",
      born: "June 24, 1987 in Rosario, Argentina",
      birthname: "Lionel Andrés 'Leo' Messi",
      nickname: "Leo",
      height: "1.70 m",
      img1: "/images/lionelmessi1.jpg",
      img2: "/images/lionelmessi2.jpg",
      img3: "/images/lionelmessi3.jpg",
      img4: "/images/lionelmessi4.jpg",
      img5: "/images/lionelmessi5.jpg",
      img6: "/images/lionelmessi6.jpg",
      img7: "/images/lionelmessi7.jpg",
      img8: "/images/lionelmessi8.jpg",
      img9: "/images/lionelmessi9.jpg",
      img10: "/images/lionelmessi10.jpg",



      birth: "Born June 24, 1987",
      parents: "(Jorge Messi/Celia Cuccittini)",
      school: "Local school in Rosario",
      university: "Did not attend university (focused on football)",
      address: "Rosario, Argentina.",
      careerbefore: "Played for Newell’s",
      firstcareer: "Professional debut with FC Barcelona",
      currentcareer: "Plays for Inter Miami",
      marriages: "Married Antonela Roccuzzo",
      children: "Thiago, Mateo, and Ciro",
    },
    {
      name: "Michael Jordan",
      imageSrc: "/images/jordanS.webp",
      imageAlt: "Michael Jordan",
      videoPoster: "/images/postermichealS.jpg",
      videoSrcMp4: "/images/Best of Michael Jordan’s Playoff Games .mp4",
      videoSrcOgg: "/Best of Michael Jordan’s Playoff Games .ogg",
      videoSrcWebm: "/Best of Michael Jordan’s Playoff Games .webm",
      videoDescription: "Best of Michael Jordan’s Playoff Games",
      born: "February 17, 1963 in Brooklyn, New York, USA",
      birthname: "Michael Jeffrey Jordan",
      nickname: "MJ",
      height: "1.98 m",
      img1: "/images/michaeljordan1.jpg",
      img2: "/images/michaeljordan2.jpg",
      img3: "/images/michaeljordan3.jpg",
      img4: "/images/michaeljordan4.jpg",
      img5: "/images/michaeljordan5.jpg",
      img6: "/images/michaeljordan6.jpg",
      img7: "/images/michaeljordan7.jpg",
      img8: "/images/michaeljordan8.jpg",
      img9: "/images/michaeljordan9.jpg",
      img10: "/images/michaeljordan10.jpg",

      birth: "Born February 17, 1963",
      parents: "(James Jordan/Deloris Jordan)",
      school: "Laney High School in Wilmington",
      university: "University of North Carolina",
      address: "University of North Carolina",
      careerbefore: "High school basketball standout.",
      firstcareer: "Joined the NBA",
      currentcareer: "Retired basketball player, businessman",
      marriages: "Yvette Prieto",
      children: "Jeffrey, Marcus, Jasmine",
    },
    {
      name: "Muhammad Ali",
      imageSrc: "/images/aliS.webp",
      imageAlt: "Muhammad Ali",
      videoPoster: "/images/posteraliS.jpg",
      videoSrcMp4: "/images/The Greatest - Muhammad Ali Inspirational Video.mp4",
      videoSrcOgg: "/The Greatest - Muhammad Ali Inspirational Video.ogg",
      videoSrcWebm: "/The Greatest - Muhammad Ali Inspirational Video.webm",
      videoDescription: "The Greatest - Muhammad Ali Inspirational Video",
      born: "January 17, 1942 in Louisville, Kentucky, USA",
      birthname: "Cassius Marcellus Clay Jr.",
      nickname: "Muhammad Ali",
      height: "1.91 m",
      img1: "/images/muhammadali1.jpg",
      img2: "/images/muhammadali2.jpg",
      img3: "/images/muhammadali3.jpg",
      img4: "/images/muhammadali4.jpg",
      img5: "/images/muhammadali5.jpg",
      img6: "/images/muhammadali6.jpg",
      img7: "/images/muhammadali7.jpg",
      img8: "/images/muhammadali8.jpg",
      img9: "/images/muhammadali9.jpg",
      img10: "/images/muhammadali10.jpg",


      birth: "Born January 17, 1942",
      parents: "(Marcellus Clay/Odessa Grady Clay)",
      school: "Central High School",
      university: "Did not attend university",
      address: "Kentucky, USA",
      careerbefore: "Started boxing at age 12",
      firstcareer: "Professional boxing",
      currentcareer: "Known as a legendary boxer",
      marriages: "Lonnie Williams",
      children: "Laila Ali",
    },
    {
      name: "Alexia Putellas",
      imageSrc: "/images/alexiaS.jpg",
      imageAlt: "Alexia Putellas",
      videoPoster: "/images/posteralexiaS.jpg",
      videoSrcMp4: "/images/This is Why Alexia Putellas is GOAT of Women Football!.mp4",
      videoSrcOgg: "/This is Why Alexia Putellas is GOAT of Women Football!.ogg",
      videoSrcWebm: "/This is Why Alexia Putellas is GOAT of Women Football!.webm",
      videoDescription: "This is Why Alexia Putellas is GOAT of Women Football!",
      born: "February 4, 1994 in Mollet del Vallès, Spain",
      birthname: "Alexia Putellas Segura",
      nickname: "Alexia",
      height: "1.73 m",
      img1: "/images/alexiaputellas1.jpg",
      img2: "/images/alexiaputellas2.jpg",
      img3: "/images/alexiaputellas3.jpg",
      img4: "/images/alexiaputellas4.jpg",
      img5: "/images/alexiaputellas5.jpg",
      img6: "/images/alexiaputellas6.jpg",
      img7: "/images/alexiaputellas7.jpg",
      img8: "/images/alexiaputellas8.jpg",
      img9: "/images/alexiaputellas9.jpg",
      img10: "/images/alexiaputellas10.jpg",



      birth: "Born February 4, 1994",
      parents: "(Jaume Putellas/Eli Segura)",
      school: "Central High School",
      university: "Local school in Mollet",
      address: "Mollet del Vallès, Spain",
      careerbefore: "Played for CE Sabadell",
      firstcareer: "Professional debut",
      currentcareer: "Plays for FC Barcelona",
      marriages: "Not married",
      children: "No children",
    },
    {
      name: "Lewis Hamilton",
      imageSrc: "/images/lewisS.jpg",
      imageAlt: "Lewis Hamilton",
      videoPoster: "/images/posterlewisS.jpg",
      videoSrcMp4: "/images/Lewis Hamilton Drives the Ferrari SF-24 at Mugello! .mp4",
      videoSrcOgg: "/Lewis Hamilton Drives the Ferrari SF-24 at Mugello! .ogg",
      videoSrcWebm: "/Lewis Hamilton Drives the Ferrari SF-24 at Mugello! .webm",
      videoDescription: "Lewis Hamilton Drives the Ferrari SF-24 at Mugello!",
      born: "January 7, 1985 in Stevenage, Hertfordshire, England",
      birthname: "Lewis Carl Davidson Hamilton",
      nickname: "Lewis",
      height: "1.74 m",
      img1: "/images/lewishamilton1.jpg",
      img2: "/images/lewishamilton2.jpg",
      img3: "/images/lewishamilton3.jpg",
      img4: "/images/lewishamilton4.jpg",
      img5: "/images/lewishamilton5.jpg",
      img6: "/images/lewishamilton6.jpg",
      img7: "/images/lewishamilton7.jpg",
      img8: "/images/lewishamilton8.jpg",
      img9: "/images/lewishamilton9.jpg",
      img10: "/images/lewishamilton10.jpg",


      birth: "Born January 7, 1985",
      parents: "(Anthony Hamilton/Carmen Larbalestier)",
      school: "The John Henry Newman",
      university: "Did not attend university",
      address: "Hertfordshire, England",
      careerbefore: "Karting champion",
      firstcareer: "Formula 1 debut with McLaren",
      currentcareer: "Seven-time Formula 1 World Champion",
      marriages: "Not married",
      children: "No children",
    },
    {
      name: "Cristiano Ronaldo",
      imageSrc: "/images/ronaldoS.jpg",
      imageAlt: "Cristiano Ronaldo",
      videoPoster: "/images/posterronaldoS.jpg",
      videoSrcMp4: "/images/Two years of CR7 in Saudi Arabia_ The interview 🎙️🐐.mp4",
      videoSrcOgg: "/Two years of CR7 in Saudi Arabia_ The interview 🎙️🐐.ogg",
      videoSrcWebm: "/Two years of CR7 in Saudi Arabia_ The interview 🎙️🐐.webm",
      videoDescription: "Two years of CR7 in Saudi Arabia",
      born: "January 7, 1985 in Funchal, Madeira, Portugal",
  birthname: "Cristiano Ronaldo dos Santos Aveiro",
  nickname: "CR7",
  height: "1.87 m",
  img1: "/images/cristianoronaldo1.jpg",
  img2: "/images/cristianoronaldo2.jpg",
  img3: "/images/cristianoronaldo3.jpg",
  img4: "/images/cristianoronaldo4.jpg",
  img5: "/images/cristianoronaldo5.jpg",
  img6: "/images/cristianoronaldo6.jpg",
  img7: "/images/cristianoronaldo7.jpg",
  img8: "/images/cristianoronaldo8.jpg",
  img9: "/images/cristianoronaldo9.jpg",
  img10: "/images/cristianoronaldo10.jpg"  ,

  birth: "Born February 5, 1985",
  parents: "(José Dinis Aveiro/Maria Dolores)",
  school: "Local school in Madeira",
  university: "Did not attend university",
  address: "Madeira, Portugal",
  careerbefore: "Played for Andorinha",
  firstcareer: "Professional debut with Sporting CP in 2002",
  currentcareer: "Plays for Al-Nassr in Saudi Arabia",
  marriages: "Georgina Rodríguez",
  children: "Cristiano Jr., Eva, Mateo, Alana Martina",
    },
  ];
  