export const actorsData = {
  
    imgprof1: "/images/bradpitt1.jpg",
    name1: "Brad Pitt",
    text1: "Brad Pitt is an acclaimed American actor and producer, born on December 18, 1963. Known",
    text2: "for his versatility, he has starred in iconic films such as Fight Club, Ocean's Eleven.",
    text3: "He has won two Academy Awards: one as a producer for 12 Years a Slave and another as Best Supporting Actor",
    text4: "for Once Upon a Time in Hollywood. Pitt is also known for his philanthropy and luxury campaigns.",
    text5: "He has worked with brands like Chanel and Brioni.",
    nameads1: "Chanel no.5",
    brand1: "/images/brand1.png",
    brand2: "/images/brand2.png",
    buy1: "buy",
    img1: "/images/brr.png",
  
    imgprof2: "/images/theo.png",
    name2: "Theo James",
    text6: "Theo James is an English actor, born on December 16, 1984. He is best known for his role as Four in the Divergent series.",
    text7: "He has also appeared in films such as Underworld: Awakening and Sanditon.",
    text8: "Known for his charm and acting skills, Theo James has a strong fanbase globally.",
    text9: "He is associated with various luxury brands and campaigns.",
    text10: "Theo has collaborated with brands like Hugo Boss for their campaigns.",
    nameads2: "Hugo Boss",
    brand3: "/images/brand1.png",
    brand4: "/images/brand2.png",
    buy2: "buy",
    img2: "/images/theo.png",
  
    imgprof3: "/images/angelina.png",
    name3: "Angelina Jolie",
    text11: "Angelina Jolie is an American actress, filmmaker, and humanitarian, born on June 4, 1975.",
    text12: "She is renowned for her roles in films like Maleficent, Mr. & Mrs. Smith, and Tomb Raider.",
    text13: "Jolie has received numerous awards, including an Academy Award and three Golden Globe Awards.",
    text14: "She is also a UNHCR Goodwill Ambassador and a prominent advocate for human rights.",
    text15: "Angelina has been the face of brands like Louis Vuitton and Guerlain.",
    nameads3: "Louis Vuitton",
    brand5: "/images/brand1.png",
    brand6: "/images/brand2.png",
    buy3: "buy",
    img3: "/images/angelina.png",
  };
  
export const playersData = {
   
    imgprof1: "/images/m10.png",
    name1: "Lionel Messi",
    text1: "Lionel Messi is an Argentine professional footballer, widely regarded as one of the greatest players of all time.",
    text2: "Born on June 24, 1987, he has won multiple Ballon d'Or awards and numerous championships with FC Barcelona and PSG.",
    text3: "Messi is also a World Cup champion, leading Argentina to victory in 2022.",
    text4: "He is a global icon and brand ambassador for Adidas and several other companies.",
    text5: "His philanthropy includes work through the Leo Messi Foundation.",
    nameads1: "Adidas",
    brand1: "/images/brand1.png",
    brand2: "/images/brand2.png",
    buy1: "buy",
    img1: "/images/m10.png",
  
    imgprof2: "/images/mi23.png",
    name2: "Michael Jordan",
    text6: "Michael Jordan is an American former basketball player, often considered the greatest of all time.",
    text7: "Born on February 17, 1963, he led the Chicago Bulls to six NBA championships and won five MVP awards.",
    text8: "Jordan is a global cultural icon and has a lifetime partnership with Nike.",
    text9: "He is known for his signature Air Jordan sneakers and his ownership of the Charlotte Hornets.",
    text10: "Beyond sports, Jordan is involved in numerous philanthropic initiatives.",
    nameads2: "Nike",
    brand3: "/images/brand1.png",
    brand4: "/images/brand2.png",
    buy2: "buy",
    img2: "/images/mi23.png",
  
    imgprof3: "/images/r7.png",
    name3: "Ronaldo",
    text11: "Ronaldo is a Portuguese professional boxer and cultural icon, born on January 17, 1942.",
    text12: "Known for his charisma and skill, Ronaldo was a three-time heavyweight champion and Olympic gold medalist.",
    text13: "He was also a prominent activist, standing for civil rights and global peace.",
    text14: "Ronaldo's legacy extends beyond sports, as he remains an inspiration for generations.",
    text15: "He has been featured in campaigns for major brands like Gatorade and Adidas.",
    nameads3: "Gatorade",
    brand5: "/images/brand1.png",
    brand6: "/images/brand2.png",
    buy3: "buy",
    img3: "/images/r7.png",
  };
  
 export const musiciansData = {
    imgprof1: "/images/alele1.png",
    name1: "Adele",
    text1: "Adele is a British singer and songwriter, celebrated for her powerful voice and heartfelt lyrics.",
    text2: "Born on May 5, 1988, she has won numerous awards, including multiple Grammys and an Academy Award.",
    text3: "Her albums, such as '21' and '30,' have achieved global success and critical acclaim.",
    text4: "Adele is known for her soulful performances and deep connection with her fans.",
    text5: "She has collaborated with top brands like Burberry and Spotify.",
    nameads1: "Spotify",
    brand1: "/images/brand1.png",
    brand2: "/images/brand2.png",
    buy1: "buy",
    img1: "/images/alele1.png",
  
    imgprof2: "/images/bele1.png",
    name2: "Billie Eilish",
    text6: "Billie Eilish is an American singer and songwriter, known for her unique style and captivating music.",
    text7: "Born on December 18, 2001, she gained fame with her debut single 'Ocean Eyes.'",
    text8: "Eilish has won several Grammys and became a cultural phenomenon for her innovative sound.",
    text9: "She is an advocate for mental health awareness and environmental issues.",
    text10: "Billie has partnerships with brands like Gucci and Apple Music.",
    nameads2: "Gucci",
    brand3: "/images/brand1.png",
    brand4: "/images/brand2.png",
    buy2: "buy",
    img2: "/images/bele1.png",
  
    imgprof3: "/images/theweek1.png",
    name3: "The Weeknd",
    text11: "The Weeknd, born Abel Tesfaye, is a Canadian singer, songwriter, and producer.",
    text12: "Born on February 16, 1990, he is known for hits like 'Blinding Lights' and 'Save Your Tears.'",
    text13: "He has won numerous awards, including multiple Grammys and Billboard Music Awards.",
    text14: "The Weeknd is celebrated for his unique voice and genre-blending music style.",
    text15: "He has collaborated with brands like Puma and Mercedes-Benz.",
    nameads3: "Puma",
    brand5: "/images/brand1.png",
    brand6: "/images/brand2.png",
    buy3: "buy",
    img3: "/images/theweek1.png",
  };



 